### PR TITLE
feat: derive Copy trait for messages where possible

### PR DESCRIPTION
**Pull request by caspermeijn**
Rust primitive types can be copied by simply copying the bits. Rust structs can also have this property by deriving the Copy trait.

Automatically derive Copy for:
- messages that only have fields with primitive types
- the Rust enum for one-of fields
- messages whose field type are messages that also implement Copy

Generated code for Protobuf enums already derives Copy.

### CODE REVIEW

**Comment by gibbz00** [comment]
Would it be possible to make this configurable? I personally like to avoid automatic Copy derives to avoid implicit cloning.

**Comment by caspermeijn** [comment]
> Would it be possible to make this configurable? I personally like to avoid automatic Copy derives to avoid implicit cloning.

What do you mean with implicit cloning? The trait `Copy` means that the bytes can simply be copied to create a second object.

The docs says: When should my type be Copy? Generally speaking, if your type can implement Copy, it should.

https://doc.rust-lang.org/std/marker/trait.Copy.html

**Comment by gibbz00** [comment]
This example is perhaps trivial, but my experience is that these things can become really tricky to pin down in large projects.

```rust
fn main() {
    let copyable = 1;
    read(&copyable);
}

fn read(x: &u32) {
    update(*x); // implicit clone
    dbg!(x); // 1
}

fn update(mut x: u32) {
    x += 1;
    dbg!(x); // 2
}
```

**Comment by caspermeijn** [comment]
>     update(*x); // implicit clone

I would not call that an implicit clone, as you explicitly deref `x`. With a deref, you choose to copy the value from behind the reference to a local variable. So with `*` you choose to copy, am I right?

https://micouy.github.io/rust-dereferencing/

**Comment by gibbz00** [comment]
Well things get a bit tricky because derefmut and deref both use the same symbol `*`.

Sure, my example was maybe not the best. I'm also just playing a bit of devil's advocate. 

There's still the basic case of implicit cloning mentioned in [the link you posted above](https://doc.rust-lang.org/std/marker/trait.Copy.html#whats-the-difference-between-copy-and-clone):

```rust
#[derive(Copy, Clone)]
struct GiantStruct(u32);

fn main() {
    let copyable0 = GiantStruct(1);
    let copyable1 = copyable0;
}
```

**Comment by caspermeijn** [comment]
> There's still the basic case of implicit cloning mentioned in [the link you posted above](https://doc.rust-lang.org/std/marker/trait.Copy.html#whats-the-difference-between-copy-and-clone):

Well, that is how the language is supposed to work, right? If you want two variables pointing to the same instance, then you want to take a reference: `let copyable1 = &copyable0;`. 

Sorry, but I don't understand in what situation you don't want an `impl Copy` for your types. From my perspective, it is always useful.

**Comment by gibbz00** [comment]
You're probably right. I usually want the compiler to tell me that I must copy things if that's what I'm trying to do.

The Rust API Guidelines book also recommends implementing `Copy` for public types: https://rust-lang.github.io/api-guidelines/interoperability.html?highlight=copy#types-eagerly-implement-common-traits-c-common-traits

**Review by LucioFranco — APPROVED** [review]
Really nice work! I like this a lot. Do you think we should release this as part of a breaking change or not?

**Comment by caspermeijn** [comment]
> Really nice work! I like this a lot. Do you think we should release this as part of a breaking change or not?

I agree this is a breaking change.

**Comment by ShaneMurphy2** [comment]
I know this is closed, but I think this is absolutely not a change that should be automatically implemented. The trait Copy is _not_ an auto trait for a reason. It carries a semantic choice about whether your type has move semantics or copy semantics. This choice is opt-in at the language level by design. Rust is a language about explicitness, and implicitly making a choice during codegen that inserts implicit behavior is antithetical to that principle. There is a [great article](https://smallcultfollowing.com/babysteps/blog/2024/06/21/claim-auto-and-otherwise/) about Copy/Clone that outlines how in today's Rust, Copy is really two ideas in one. One is what you mentioned that it is "a bitwise copy", the other is "this type has value semantics". Those are (and should in the language) separate concepts.

**Comment by LucioFranco** [comment]
@ShaneMurphy2 would be helpful if you could call out specific cases where prost is generating a copy impl for a type that isn't trivially copyable.

**Comment by ShaneMurphy2** [comment]
> @ShaneMurphy2 would be helpful if you could call out specific cases where prost is generating a copy impl for a type that isn't trivially copyable.

That isn't the issue. The type is trivially copyable. Being trivially copyable and "having value semantics" are independent concepts. If I want move semantics for my type, because instances of it are not interchangeable (one definition of value semantics), then I should be able to have that for my type. It is a semantic property ascribed to the type separate from the mechanical property of "you can make a clone by doing a bitwise memcpy".

**Pull request merged**
