### PR TITLE
Make Debug impl optional for types

### PR DESCRIPTION
**Pull request by audunska**
See #795 for motivation. If this looks like an ok approach, I'll go ahead and add more documentation.

Where is a good place to put some tests for this behavior?

### CODE REVIEW

**Review by LucioFranco — COMMENTED** [review]
This seems like a fine approach, I would like to see a lot of tests added around the different combinations of debug impls and to also make sure the root level debug isn't a problem.

**Comment by AlJohri** [comment]
Friendly bump on this @audunska-- would you be able to add some tests? This would be a really useful feature.

**Comment by audunska** [comment]
I didn't end up prioritizing it, but I can do it now :)

**Comment by audunska** [comment]
Ok, I've added some tests testing both the Message trait directly, and testing code generation. Anything else?

**Review by LucioFranco — APPROVED** [review]
Thanks for adding the tests!

**Pull request merged**
