### PR TITLE
refactor: Optimize code based on cargo clippy suggestions

### PR DESCRIPTION
**Pull request by tgolang**

### CODE REVIEW

**Review by caspermeijn — COMMENTED** [review]
After this change, the next tool (rustfmt) has some suggestions 😉.

Could you also fix the `dereferencing a tuple pattern where every element takes a reference` suggestions from clippy?

**Comment by gibbz00** [comment]
Note that #1008 does this too.

**Comment by caspermeijn** [comment]
Fixed by https://github.com/tokio-rs/prost/pull/1008

**Comment by tgolang** [comment]
Thanks!

**Pull request closed without merging**
