### PR TITLE
Add enum variant to string mapping

### PR DESCRIPTION
**Pull request by vriesk**

### CODE REVIEW

**Comment by vriesk** [comment]
@LucioFranco friendly ping :)

**Comment by LucioFranco** [comment]
Sorry for the delay on this was out on vacation and still suffering from some jetlag. I took a cursory review but would like to spend some more time looking at this. Just wanted to let you know what the status was.

As for one thing, since this adds a method on the generated codegen types. I am leaning that we should just add this not as an opt-in but as a on by default without the config. This would also mean that `prost-types` would need to be updated and I would like to see that since it will show case some of the codegen.

**Comment by vriesk** [comment]
Ack, I can remove the config guard. Do you have some specific method to regenerate the `prost-types` or is it just output of `prost-build` run?

**Comment by vriesk** [comment]
> 

Done.

**Comment by vriesk** [comment]
@LucioFranco I have just noticed that `clippy` whines about the `to_str_name()` name:

```
warning: methods with the following characteristics: (`to_*` and `self` type is `Copy`) usually take `self` by value
```

Maybe let's change it to `as_str_name()` then before this gets released? WDYT?

**Comment by LucioFranco** [comment]
@vriesk good idea, lets do that.

**Pull request merged**
