### PR TITLE
Add support for Apple Silicon

### PR DESCRIPTION
**Pull request by joelreymont**
* Add pre-compiled protoc binary for ARM
* Enable build support for native binary.

### CODE REVIEW

**Comment by joelreymont** [comment]
This should resolve https://github.com/tokio-rs/console/issues/62 @LucioFranco

**Comment by LucioFranco** [comment]
This seems fine to me, since @repi wrote the original I'd like them to take a look before we merge if possible.

**Comment by LucioFranco** [comment]
@joelreymont looks like a CI failure due to rustfmt, can you get that fixed?

**Comment by joelreymont** [comment]
> @joelreymont looks like a CI failure due to rustfmt, can you get that fixed?

Will fix!

**Comment by joelreymont** [comment]
@LucioFranco Fixed, check!

**Pull request merged**
