### PR TITLE
Add a configuration hook to run after protobuf compilation

### PR DESCRIPTION
**Pull request by andrewhickman**
This is intended as a simpler alternative to PRs like #494 and #549. Instead of adding additional ways to filter types, we can just expose the file descriptor set to the user and give them the power to do the filtering.

By allowing the user to inspect the file descriptor set themselves, its possible to do stuff like adding attributes to messages but not enums and oneofs

For example, with [`prost-reflect`](https://crates.io/crates/prost-reflect) it can be used to annotate the messages with the message name to add reflection support

```
config
    .post_compile_hook(|config, file_set| {
        for file in &file_set.file {
            for message in &file.message_type {
                config.type_attribute(
                    &format!(".{}.{}", file.package(), message.name()),
                    &format!("#[derive(::prost_reflect::ReflectMessage)] #[prost_reflect(file_descriptor = \"TEST_FILE_DESCRIPTOR\", message_name = \"test.{}\")]", message.name()),
                );
            }
        }
    })
```

### CODE REVIEW

**Comment by LucioFranco** [comment]
Why does this need to be a hook on config and not a free fn that you can call then allow you to call the methods on config?

**Comment by andrewhickman** [comment]
I'm not sure what you mean by a free fn, could you give an example of the api you had in mind?

**Comment by LucioFranco** [comment]
```rust
let file_set = prost_build::get_file_descriptor(...path config);

for file in &file_set.file {
            for message in &file.message_type {
                config.type_attribute(
                    &format!(".{}.{}", file.package(), message.name()),
                    &format!("#[derive(::prost_reflect::ReflectMessage)] #[prost_reflect(file_descriptor = \"TEST_FILE_DESCRIPTOR\", message_name = \"test.{}\")]", message.name()),
                );
            }
        }
```

Something like this maybe? and we can avoid the hook config

**Comment by andrewhickman** [comment]
I think that works too, though there are a couple slight annoyances:
- The user has to provide the protos/include paths twice
- Unless the user calls `skip_protoc_run` on the config, we'd be running `protoc` twice

The main reason for the hook-based approach was so that as a library author, I can just provide an extension method like
`add_reflect_message_impls(config: prost_build::Config)` without the user needing to make any other changes to how they use `prost_build`

**Comment by LucioFranco** [comment]
Yeah, I am just hesitant to adding these sort of "hooks" when I don't think they are 100% needed. I would imagine maybe going a non extension trait way might be better in this case and provide a custom config that kinda handles this. I would really to reduce the verbosity of the config struct as I think its gotten a bit out of hand and am hesitant to adding more to it. I don't think running protoc twice is that bad and as you said its still possible to disable it.

**Pull request closed without merging**
