### PR TITLE
chore: Split prost-types lib.rs into separate modules.

### PR DESCRIPTION
**Pull request by gibbz00**
Protobuf JSON mapping requires a lot of custom serializing for each protobuf type. Continuing to add that logic in a huge lib.rs file would quickly make these things harder to maintain and reason about.

Depends on #1006

### CODE REVIEW

**Review by caspermeijn — COMMENTED** [review]
Please rebase to latest master

**Review by caspermeijn — APPROVED** [review]
Looks good to me

**Comment by gibbz00** [comment]
Shit, rebased anyway after the LGTM, sorry. Pressed the rebase button on Github, nothing else.

**Comment by caspermeijn** [comment]
> Shit, rebased anyway after the LGTM, sorry. Pressed the rebase button on Github, nothing else.

No problem. My first reaction was: it needs a rebase. My second reaction was: well, GitHub will do that automatically.

**Comment by gibbz00** [comment]
Hehe. It do be like that sometimes. Thanks 😊

**Pull request merged**
